<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head profile="http://purl.org/NET/erdf/profile">
        <title><?php echo $this->title ?></title>
    </head>
    <body>
        <div class="header">
            <h1>header goes here</h1>
        </div>
        <div class="content">
            <h1>content goes here</h1>
            <?php echo $this->content ?>
        </div>
        <div class="footer">
            <h1>footer goes here</h1>
        </div>
    </body>
</html>